import {Name} from "./Name";
import {Address} from "./Address";
export class Policy {
    //policy data only...
    // policies should be cloneable without workflow context but you can never use the exact version outside of Work.
    desc:string;  //notes/comments.
    // can be generated by default.  for example, when doing quoting it will be a diff summary.
    //  create a JSON patch and unroll it.
    // e.g. Deductible increased to $1000 and 3 other changes.   //

    name : Name;
    address : Address;
}

